version: '3.8'

services:
  web:
    image: minhhung1/chatweb:latest # or build locally if needed
    build:
      context: .  # remove this if you want to use a prebuilt image only
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    # Uncomment if you need volumes for development
    # volumes:
    #   - .:/app

# (Optional) Add more services like a database if needed
# db:
#   image: postgres
#   environment:
#     POSTGRES_USER: user
#     POSTGRES_PASSWORD: pass
#     POSTGRES_DB: mydb
#   ports:
#     - "5432:5432"
